name: Testing pipeline

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

permissions:
  contents: 'read'

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry==1.7.1
        poetry install
    - name: Run linters
      run: make lint-check
    - name: Run tests with coverage
      run: make coverage
    - name: Coveralls
      uses: coverallsapp/github-action@v1
      with:
        path-to-lcov: "./coverage.lcov"
        github-token: ${{ secrets.GITHUB_TOKEN }}

